services:
  chroma:
    build:
      context: .
      dockerfile: Dockerfile.chroma
    ports:
      - "8000:8000"
    # No need for volume mapping since data is inside the image
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000